name: Build and Release Binary

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.2'
        
    - name: Install dependencies
      run: |
        go mod download
        go mod verify
    
    - name: Build Binary
      run: |
        env GOOS=linux GOARCH=386 go build -v -ldflags "-s -w" -o kiosk-client cmd/main.go

    - name: Push Binary to Releases Branch
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        git clone https://${{ secrets.PAT }}@github.com/${{ github.repository }} repo
        cd repo

        git checkout releases || git checkout -b releases

        git rm -f kiosk-client || true

        cp ../kiosk-client .
        git add kiosk-client

        git commit -m "Update kiosk-client binary for $(date +%Y-%m-%d)" || true
        git push origin releases
