name: Go

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.2'
        
    - name: Install dependencies
      run: |
        go mod download
        go mod verify
    
    - name: Build and push binary
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        git fetch origin releases
        git checkout -b releases origin/releases || git checkout releases
        
        git rm --cached kiosk-client || echo "No previous binary to remove"

        git merge origin/master
        
        env GOOS=linux GOARCH=arm64 go build -v -ldflags "-s -w" -o kiosk-client cmd/main.go
        
        git add kiosk-client
        git commit -m "Update kiosk-client binary" || echo "No changes to commit"
        
        git push -f https://${{ secrets.PAT }}@github.com/${{ github.repository }} releases
